### ISSUE TITLE
Support determining the current path type at runtime

### ISSUE THREAD

**Issue by luite** [haskell/filepath#13]
While the filepath package is for cross platform path handling, it's written with the assumption that the default filepath type can be determined at compile time.

For most platforms this is true, but for programs built to run on multiple operating systems it might not be. In particular, for Cabal to work correctly with GHCJS, it needs to handle paths for the operating system that can only be determined at runtime (*).

I have a small patch in the `ghcjs-boot` libraries that accomplishes this, with an extra `System.FilePath.Current` module that determines the `isWindows` property dynamically (so it's likely to be a little slower than the two platform-specific modules). `System.FilePath` then just re-exports `System.FilePath.Current`

https://github.com/ghcjs/ghcjs-boot/blob/master/patches/filepath.patch

Is there a better way of doing this? 

(*) Cabal `Setup.hs` scripts are compiled to JavaScript by GHCJS and then run with node.js, the generated code is not (and should not be) target operating system specific.

**Comment by ndmitchell** [comment]
No response, and pretty sure this would be abused, so closing for now.
