### ISSUE TITLE
Update package metadata on Hackage

### ISSUE THREAD

**Issue by ulysses4ever** [haskell/filepath#182]
Hello! It would be marvelous to have a Hackage revision (or update, as you see fit) for the following:

1. `base` upper bound `4.18 -> 4.19` -- this is already on `master` (62c589aaaf)
2. Links in the following sections changed from gitlab to github:
    1. Home page
    2. Bug tracker
    3. Source repo

**Comment by hasufell** [comment]
https://hackage.haskell.org/package/filepath-1.4.100.0/revisions/

**Comment by hasufell** [comment]
@ulysses4ever can you copy paste the cabal file here or somewhere? Is this on master already? I lost track. My head is in the clouds.

**Comment by ulysses4ever** [comment]
@hasufell 

> can you copy paste the cabal file here or somewhere?

I submitted a patch in #186. I hope that it's no less helpful than a copy-paste. This is not an urgent issue of course. It's just a bit confusing (the current state where there are three links to GitLab, I mean).
