### ISSUE TITLE
Problems when trying to use the package with stack

### ISSUE THREAD

**Issue by andrewerf** [haskell/filepath#196]
It seems that the version indexed by the Haskell LTS (which is used by `stack`) is the one with absent `OsPath` feature: https://www.stackage.org/lts-20.25/hoogle?q=filepath.

This creates an obstacle to use this feature, which at first sight seem quite nice. Is there a reason why the latest version with `OsPath` is not marked as preferred and not included in LTSs?

**Comment by hasufell** [comment]
I don't know. I'm not a stackage curator.

Filepath 1.4.100.1 is first shipped by GHC 9.6.1.

With cabal I can easily use it with older GHCs as well.

@mpilgrem @juhp

**Comment by juhp** [comment]
The version in Stackage should just be the package version directly from GHC.
We do not try to override any core library versions in Stackage.

**Comment by hasufell** [comment]
> but it will obviously cause various core libraries to be rebuilt

Which should be fine, since existing API was untouched.
