### ISSUE TITLE
Make osp :: QuasiQuoter valid as a pattern

### ISSUE THREAD

**Issue by lawbel** [haskell/filepath#205]
I was quite surprised to find that the following code is not valid:

```haskell
import System.OsPath (OsPath, osp, takeExtension)

data Format = Png | Jpeg

extensionType :: OsPath -> Maybe Format
extensionType path = case takeExtension path of
    [osp|.png|] -> Just Png
    [osp|.jpg|] -> Just Jpeg
    _           -> Nothing
```

I can see that the `osp` QuasiQuoter is implemented to only support expressions, but this kind of use case feels very natural. Especially given that it is non-trivial to construct a valid `OsPath` literal.

Is there any reason why this couldn't or shouldn't be implemented? If no, then I would be more than happy to have a go at it and put together a PR.

**Comment by hasufell** [comment]
I don't know much about TH. Is this possible?

**Comment by lawbel** [comment]
I also don't know TH well enough to answer that 😅 I would think that if we can generate expressions, then surely (hopefully) we can use a similar approach to translate those expressions into a sensible pattern.

**Comment by Bodigrim** [comment]
https://github.com/haskell/filepath/blob/51501dba4f963087eac2b67ed13b64fe0304d63b/System/OsPath/Internal.hs#L130-L140

I imagine one should define `quotePat` as well.

**Comment by lawbel** [comment]
I've been working on this, but could do with some guidance on how best to proceed.

So this turns out to be a bit tricky actually, because of what is allowable as a valid pattern. We would need to either drill down into the underlying constructor and match against the payload, or use a view pattern to do some computation.

Using a view pattern is not ideal, because it forces the user to turn on `ViewPatterns`. But otherwise it is simple to implement and it works.

Getting to the underlying constructor has proven difficult. I understand that `OsPath`/`OsString` is ultimately a wrapper around a `ByteArray#` from base. But `ByteArray#` is an abstract type that is not matchable on (correct me if I'm wrong?). So this seems to be impossible.

What do you think, go ahead with the view pattern approach?

**Comment by lawbel** [comment]
On reflection, what we can do is define a pattern synonym (not certain whether it would have to exported to make this work):

```haskell
pattern Packed :: [OsChar] -> OsPath
pattern Packed chars <- (System.OsPath.unpack -> chars)
    where Packed chars = System.OsPath.pack chars
```

which hides the view pattern, and then can match on `[OsChar]` as it's just a `[Word8]` or a `[Word16]` depending on platform. That seems like the best option.

**Comment by Bodigrim** [comment]
I would expect `[osp|foo|]` as a pattern to generate `xs | xs == [osp|foo|]`. Is it not feasible?

**Comment by lawbel** [comment]
@Bodigrim I would like to be be able to do that, but it turns out it isn't possible. If you look at [QuasiQuoter][quasiquoter] you can see that `quotePat` returns a [Pat][pat]. There are various options for what sort of pattern a `Pat` can be, such as

* a literal, `'c'` or `12`
* a constructor, `Constr pat1 pat2 pat3`
* a tuple, `(pat1, pat2)`
* etc.

But there is no option to add a pattern guard. I guess the reason is that the pattern we generate should be valid even if it's nested within some other pattern, but guards are only allowed at the top level.

[quasiquoter]: https://hackage.haskell.org/package/template-haskell/docs/Language-Haskell-TH-Quote.html#t:QuasiQuoter
[pat]: https://hackage.haskell.org/package/template-haskell/docs/Language-Haskell-TH-Syntax.html#t:Pat

**Comment by Bodigrim** [comment]
@lawbel ah, I see. I think `ViewP` is a solid option then: GHC would prompt user to enable `ViewPatterns`.

**Comment by lawbel** [comment]
Thanks @Bodigrim for all the help, I put together a PR which implements this as a view pattern.
