### ISSUE TITLE
possible reversion of W.splitFileName "/\\?/a:"

### ISSUE THREAD

**Issue by joeyh** [haskell/filepath#219]
Before 1.4.100.2, `System.FilePath.Windows.splitFileName "/\\?/a:" == ("/\\?/a:","")` and in that version and since it changed to `("/\\?/","a:")`

I don't fully understand Windows path semantics, and this path was generated by QuickCheck, so I don't know which is right, but 1.4.100.2 did not document any change besides optimizations. Which makes me suspect this is an unintentional change.

Also, https://github.com/haskell/filepath/pull/189/commits/6a1c98dc5eb8021107d59903bbbb60137a6f9dbd fixed a reversion in `W.splitFileName "\\\\?\\A:\\fred"` which seems very similar to this.

```
ghci> System.FilePath.Windows.splitFileName "\\\\?\\A:\\fred"
("\\\\?\\A:\\","fred")
ghci> System.FilePath.Windows.splitFileName "\\\\?\\A:\\"
("\\\\?\\A:\\","")
ghci> System.FilePath.Windows.splitFileName "\\\\?\\A:"
("\\\\?\\","A:")
```

**Comment by Bodigrim** [comment]
I can take a look over the next weekend.

**Comment by hasufell** [comment]
Possibly related:

* https://github.com/haskell/filepath/pull/183#issuecomment-1880167348
* https://github.com/haskell/filepath/pull/189

**Comment by joeyh** [comment]
This same issue is discussed here https://github.com/haskell/filepath/pull/183#issuecomment-1880167348

**Comment by hasufell** [comment]
Do you have a proposed fix?

**Comment by Bodigrim** [comment]
I'm working on this, hopefully will finish tomorrow.
