### ISSUE TITLE
[OsPath] add IsString instance for OsPath

### ISSUE THREAD

**Issue by srghma** [haskell/filepath#236]
https://github.com/Gabriella439/turtle/issues/455#issuecomment-2106337587

**Comment by Bodigrim** [comment]
This is by design, see https://hasufell.github.io/posts/2022-06-29-fixing-haskell-filepaths.html#why-is-there-no-isstring-instance-overloadedstrings

**Comment by hasufell** [comment]
You can write an orphan instance, if you feel lucky.

**Comment by srghma** [comment]
yes! should be `Maybe`. I dont like `IsString` too :(
