### ISSUE TITLE
`filepath-1.4.301.0` is not `-Werror` clean

### ISSUE THREAD

**Issue by bgamari** [haskell/filepath#241]
`filepath-1.4.301.0` has an unused import of `Control.Exception.try` in `System.OsPath.Encoding.Internal.Hidden`:
```
libraries/filepath/System/OsPath/Encoding/Internal/Hidden.hs:22:42: error: [GHC-38856] [-Wunused-imports, Werror=unused-imports]
    The import of ‘try’ from module ‘Control.Exception’ is redundant
   |
22 | import Control.Exception (SomeException, try, Exception (displayException), evaluate, SomeAsyncException(..), catch, fromException, toException, throwIO)
   |                                          ^^^
```
This breaks the GHC 9.8.4 validation pipeline due to GHC's use of `-Werror`. In general we prefer to keep GHC `-Werror` clean but I am happy to make an exception here if you would prefer not to produce another release. Thoughts?

**Comment by hasufell** [comment]
I want to avoid another release just to suppress warnings. Core library updates cause high churn and this doesn't seem like an interersting fix for the end user.

**Comment by bgamari** [comment]
Alright, cheers!
