### ISSUE TITLE
Tag missing for v1.5.4.0

### ISSUE THREAD

**Issue by wz1000** [haskell/filepath#242]
It is released on hackage but there is no corresponding tag.

**Comment by hasufell** [comment]
I'll add it later but you can use commit 65b0f8f31aac4a306135e27734988327f8eb1e6f

**Comment by hasufell** [comment]
Actually this is untrue. The tag already exists and was pushed last week: https://github.com/haskell/filepath/releases/tag/v1.5.4.0
