### ISSUE TITLE
Safely constructing OsPaths / OsStrings with numbers in them

### ISSUE THREAD

**Issue by noinia** [haskell/filepath#243]
I just had an instance of the following problem: I had some list of elements, and wanted to write every individual element to a file whose filename contained the index in the list. I.e. something like:

```haskell
foo xs = forM_ (zip [0..] xs) $ \(i,x) -> 
                 writeToFile (makeFileName i) x

makeFileName :: Int -> OsPath
makeFileName = ????   
```

I was looking for a bit, but I didn't really spot an easy way to actually implement 'makeFileName'. I ended up using 'show i' and encodeFS. But that actually returns a IO OsPath instead. For now that was not such an issue, since I was writing some "throw away debugging code anyway", but having to go through this route feels a bit silly. Is there a better/more convenient way of encoding numbers into OsString/OsPaths? For literal strings we the osp Quasiqouter works well, but I didn't really know how to apply that in this case.

**Comment by hasufell** [comment]
If you construct an `OsString` out of thin air, you have to decide on the underlying encoding.

There are 3 functions:

- [encodeUtf](https://hackage.haskell.org/package/os-string-2.0.7/docs/System-OsString.html#v:encodeUtf): picks UTF-8 on unix and UTF-16LE on windows
- [encodeWith](https://hackage.haskell.org/package/os-string-2.0.7/docs/System-OsString.html#v:encodeWith): you specify the encoding yourself (e.g. you could use latin-1 on unix which is just Word8 boundaries and UCS-2 on windows which is Word16 boundaries)
- [encodeLE](https://hackage.haskell.org/package/os-string-2.0.7/docs/System-OsString.html#v:encodeLE): this imitates what base does when doing FFI 

So there's no simple answer. If you pick latin1/UCS-2 via `encodeWith`, you essentially get a total conversion and you could ignore the `Left` (we don't have dependent types, so it's hard to express).

If you know the input does not have surrogates, you could also use [unsafeEncodeUtf](https://hackage.haskell.org/package/os-string-2.0.7/docs/System-OsString.html#v:unsafeEncodeUtf).

**Comment by noinia** [comment]
Ah great, in that case i guess encodeWith is what I'll use in the future :). Thanks!
