### ISSUE TITLE
Function to compute relative path not just for direct descendants but also siblings

### ISSUE THREAD

**Issue by Rufflewind** [haskell/filepath#40]
`makeRelative` doesn't support this right now; instead, it returns the original path:

    makeRelative "a/b" "a/c" == "c"

This means this law wouldn't hold:

    base </> makeRelative base path ≡ path

It would be useful to have a function that supports siblings:

    makeRelative' "a/b" "a/c" == "../c"

**Comment by ndmitchell** [comment]
In general nothing in filepath makes the assumption that `..` points to the parent. Imagine that `b` is a symlink, then `../c` would suddenly point somewhere different. That said, I agree with the utility of this method, and even wrote such a function a few days ago in [bake](https://github.com/ndmitchell/bake/blob/master/src/General/Extra.hs#L97):

    makeRelativeEx :: FilePath -> FilePath -> IO FilePath
    makeRelativeEx x y = do
        x <- splitDirectories <$> canonicalizePath x
        y <- splitDirectories <$> canonicalizePath y
        return $ joinPath $ if take 1 x /= take 1 y then y else f x y
        where
            f (x:xs) (y:ys)
                | x == y = f xs ys
                | otherwise = ".." : f xs (y:ys)
            f _ ys = ys

Feel free to reuse that. Not sure if something with the `..` assumption belongs in filepath or not.

**Comment by Rufflewind** [comment]
> In general nothing in filepath makes the assumption that `..` points to the parent. Imagine that `b` is a symlink, then `../c` would suddenly point somewhere different.

That's a good point, I hadn't thought about the effects of symlinks on `..`.
