### ISSUE TITLE
Add the function `replaceExtensions`

### ISSUE THREAD

**Issue by thomie** [haskell/filepath#42]
```
replaceExtensions x y = dropExtensions x <.> y
```

This function seems to be missing. We do have already: `takeExtensions`, `dropExtensions` and `splitExtensions`.

**Comment by thomie** [comment]
Note the `s` at the end; this would be the plural form of `replaceExtension`.

```
-- > replaceExtensions "file.fred.bob" "txt" == "file.txt"
```

Any objections to adding this? It would get used by GHC at least once (and fix a [bug](https://ghc.haskell.org/trac/ghc/ticket/9760)).

**Comment by ndmitchell** [comment]
Seems reasonable, but I'm not intending to change any code until after GHC 7.10 is released and out for a few weeks, so we don't complicate that side of things.

**Comment by ndmitchell** [comment]
Done, as you described - agreed, this is useful for symmetry.
