### ISSUE TITLE
isValid doesn't check for \0, which seems to be an invalid file name in Linux

### ISSUE THREAD

**Issue by neongreen** [haskell/filepath#44]
> isValid "\0"
    True

    > writeFile "\0" "foo"
    *** Exception: : openFile: does not exist (No such file or directory)

**Comment by ndmitchell** [comment]
Hmm, very true. I suspect it should be marked as an invalid character on both Windows and Linux. None of the docs call it out, but they are all about C functions, where the null terminator is implicit.

**Comment by hvr** [comment]
Fwiw, http://pubs.opengroup.org/onlinepubs/007904875/basedefs/xbd_chap03.html#tag_03_169 says

> A name consisting of 1 to `{NAME_MAX}` bytes used to name a file. The characters composing the name may be selected from the set of **all character values excluding the slash character and the null byte**. The filenames dot and dot-dot have special meaning. A filename is sometimes referred to as a "pathname component".

**Comment by neongreen** [comment]
> consisting of 1 to `{NAME_MAX}` bytes

By the way, `isValid` doesn't check for this either (but I wasn't sure whether it was intentional or not).

**Comment by ndmitchell** [comment]
It should check for absence of `\0` and being not the empty string.

**Comment by ndmitchell** [comment]
Checking, I see:

    $ isValid ""
    False
    $ makeValid ""
    "_"

Same behaviour on both Posix and Windows, so that part is already done.

**Comment by neongreen** [comment]
> that part is already done

Just in case, I meant the `{NAME_MAX}` part, not the `1` part when I said “doesn't check for this either”.

    > isValid (replicate 256 'a')
    True
    
    > writeFile (replicate 256 'a') "x"
    *** Exception: aaa[snip]aaa: openFile: invalid argument (File name too long)

**Comment by ndmitchell** [comment]
Isn't `{NAME_MAX}` file system dependent? I have no intention to check that.

**Comment by ndmitchell** [comment]
I've fixed `isValid "\0"` so it now returns false, and `makeValid` switches it to `_`.

**Comment by neongreen** [comment]
> Isn't `{NAME_MAX}` file system dependent?

Yes, with 255 *bytes* being the limit on most Posix systems, and 255 characters – in NTFS. But since it's indeed filesystem dependent (and also locale-dependent for Posix, I guess), I propose just pointing it out in description of `isValid` and letting people deal with it if they want.

**Comment by ndmitchell** [comment]
That seems reasonable, I've update the docs.

**Comment by ndmitchell** [comment]
Not sure why I didn't close this ticket at the time, so please comment if you think I missed some aspect of it.
