### ISSUE TITLE
new features?  relative paths, inverse paths, eliminating ".."s

### ISSUE THREAD

**Issue by zilinc** [haskell/filepath#50]
I just did the following code for my project. (The code just sketches the idea and I admit that it's not robust for library at all.) I'm not absolute sure if these features are indeed missing from this package, and if so whether they would be useful for others. So I just paste it here to seek for some comments and I can do PR if needed.

```
-- relDir src dst: calculate path from dst to src
--   if src is absolute, then return absolute path of src
--   if src is relative (from pwd), then return relative path from dst
-- `makeRelative' doesn't behave exactly as I want
relDir :: FilePath -> FilePath -> FilePath -> FilePath
relDir src dst pwd
  | isAbsolute src = dropTrailingPathSeparator src
  | otherwise {- src is relative to pwd -} = 
      if isAbsolute dst
        then dropTrailingPathSeparator $ pwd </> src
        else {- src' and dst' are both relative -} 
          let src' = norm src
              dst' = norm dst
              pwd' = splitDirectories pwd
           in makeRel src' dst' pwd'
  where -- makeRelative ss ds ps: both ss and ds are normalised relative path segs, ps is absolute path segs
        makeRel ss ds ps = let (ss',ds') = dropCommonPrefix ss ds
                            in joinPath . norm $ (inverse ds' ps) </> (joinPath ss')

        -- It inherits preconditions from `makeRel' function
        -- Postconditions: neither path is empty
        dropCommonPrefix [] [] = (["."],["."])
        dropCommonPrefix [] ds = (["."],ds)
        dropCommonPrefix ss [] = (ss,["."])
        dropCommonPrefix (s:ss) (d:ds) = if s == d then dropCommonPrefix ss ds else (s:ss,d:ds)

        -- inverse ss ps: ss is normalised relative path segs, ps is current dir (absolute, at least ["/"])
        inverse ss ps = inverse' ss ps []

        inverse' [] _ is = is
        inverse' (s:ss) ps is  -- ss is not null
                  | "."  <- s, [] <- ss = "."
                  | "."  <- s = error "inverse: path must be norm'ed"
                  | ".." <- s = inverse' ss (init ps) $ last ps </> is
                  | otherwise = inverse' ss undefined $ ".." </> is  -- no ".." should ever appear in ss thus ps is useless
        
        -- norm: similar to System.FilePath.Posix.normalise, but also elimiate ".." as much as possible
        norm (splitDirectories . normalise -> ss) = case ss of
          []  -> error "norm: path cannot be empty"
          [_] -> ss
          ss  -> let (s1,s2) = break (== "..") ss
                  in case (s1,s2) of
                       (_,[]) -> ss  -- no ".." at all
                       ([],_) -> head s2 : norm (joinPath $ tail s2)  -- ".." is the leading segment
                       _  -> init s1 ++ norm (joinPath $ tail s2)
```
Many of the preconditions are not properly checked, esp. if we want to lift those local functions to top-level.

P.S. I am not interested in Windows and have no experience on that, so the above is solely for Posix.

**Comment by ndmitchell** [comment]
The code is quite detailed, so would take a while to go through. Can you give a few examples of where `makeRelative` doesn't do what you want, and also what this function does instead? I suspect that's the best way to figure out where they differ. I see things around `..`, which I don't think `makeRelative` takes account of.

**Comment by zilinc** [comment]
Simply speaking, `makeRelaative' seems only works in one path is a "prefix" of the other, whereas my version (modulo bugs) should take any two paths, be them relative or absolute, create a relative path that can take you from one dir to another, using as little absolute path segments as possible. So a variant of my `makeRel' would be `makeRel' :: FilePath -> FilePath -> IO FilePath`, which calls `getCurrentDirectory` instead of the 3rd argument for `makeRel`. E.g.
```
src = "a/b/c/d"
dst = "a/b/e/f"
{- the argument names are a little bit domain-specific --- they're derived from my project. apologies. -}
makeRel' src dst = return "../../c/d"
makeRelative dst src = "a/b/c/d"    -- the order of args are different
------------------------------------------------
src = "a/b"
dst = "/usr/lib/e/f"
makeRel src dst pwd = pwd </> "a/b"
makeRelative dst src = "a/b"
```

`norm` I guess is clearer, which deals with ".." as said in the comment.

**Comment by zilinc** [comment]
(Just realise that my test script was wrong so the code is more buggy than I thought:( don't look at the code for now...)

**Comment by zilinc** [comment]
UPDATE: I've fixed some of the really bad code in the OP.

**Comment by ndmitchell** [comment]
I'm not worrying about the code, argument names or order etc at the moment - just the underlying idea. This code seems to make the assumption that `a/b/e/f/../../c/d` is equal to `a/b/c/d`, which relies on the assumption that `a/../b` equal to `b`. Unfortunately symlinks on Linux means that isn't always true - if `a` is a symlink to `foo/bar` then the normalised path should really be `foo/b`.

**Comment by zilinc** [comment]
I certainly agree. It's just some path manipulation, not on system level at all. I think it bears the same kind of assumption as `System.FilePath` where most functions are pure, contrary to, say `System.Directory`. It happens in some applications, such as mine, symlinks just cannot occur (or can be handled separately). In some cases, I failed to see why `makeRelative` gives me that result, like the first example above. I personally feel `../../c/d` would be a better estimate than `a/b/c/d`, which is not the relative path from arg1 to arg2.

**Comment by ndmitchell** [comment]
The problem is that given `a/c` and `a/b` as the arguments, if you spit out `../b` then you would expect `a/c/../b` to arrive at `a/b`. However, if `a/c` is a symlink to `d/e` then you arrive at `d/b`, instead of the expected `a/b`. The `FilePath` operations are all pure and correct, making no assumptions of how the files are laid out on disk. In contrast, using the `..` relative paths, makes the assumption that the first path has no symlinks in it, which I can't check (that would be a suitable thing for directory to do, but not filepath) and thus I have to return the only thing I know to be correct - the input path.

**Comment by ndmitchell** [comment]
I tried to explain more fully here - http://neilmitchell.blogspot.co.uk/2015/10/filepaths-are-subtle-symlinks-are-hard.html - since these comment boxes aren't great for a full explanation.

**Comment by zilinc** [comment]
@ndmitchell Thanks for your explanation. I was aware of the problem that symlinks introduce, but I wasn't quite sure about the rationale behind the implementation. Then I guess it's clear that filepath is not the package that my functions should land, as they assume different things. Then a follow up ticket would be: can we put this explanation in the haddock page, near the relevant functions (in particular this sentence: I have to return the only thing I know to be correct - the input path")?

**Comment by ndmitchell** [comment]
Seems thoroughly sensible - and given that the `../a` thing is part of the guiding principles behind filepath, it seems worth stating that invariant at the top.

Of course, while filepath isn't the module for these functions, I think they could be valuable to some people, so sharing them would be useful. There's clearly a common theme, given `normaliseEx` in Shake makes that assumption too.

**Comment by ndmitchell** [comment]
Documentation improved, including a link to the blog post and an example in `makeRelative` which calls out exactly what you expected and says it doesn't do it. Looking at the docs, they were all positive examples (this goes to this), so the lack of negative examples didn't make it clear what it didn't do.

**Comment by zilinc** [comment]
Thanks:)
