### ISSUE TITLE
Document behavior of addExtension  (<.>) with empty extension string

### ISSUE THREAD

**Issue by bfrk** [haskell/filepath#54]
The implementation seems to do the sensible thing `path <.> "" == path` i.e. no dot gets appended in this case, but this is not documented, nor are there examples with an empty extension argument.

**Comment by ndmitchell** [comment]
Very true - a documented example is a great idea. Pull request welcome, or I'll probably get to it in advance of the GHC 8.2 release.

**Comment by ndmitchell** [comment]
Done, as suggested.
