### ISSUE TITLE
Why doesn't System.FilePath.Internal use CPP?

### ISSUE THREAD

**Issue by sjakobi** [haskell/filepath#58]
My impression is that many functions could be slightly faster if they didn't have to use `isPosix` or `isWindows`. Or are these checks optimized away at compilation time?

**EDIT:** Using CPP instead of `isPosix` and `isWindows` might allow for better inlining too, no?

**Comment by rwbarton** [comment]
I'm rather confident in GHC's ability to simplify `not False` to `True` and to simplify away guards whose condition is a constant `False` or `True`, etc.

**Comment by ndmitchell** [comment]
I'm happy to agree this library has performance issues in certain functions, but it isn't the guards. I'd only be happy to make such changes with profiling to guide me. 

Not having as much CPP is a massive benefit to allowing all code to be type checked in one go.

**Comment by sjakobi** [comment]
> I'm happy to agree this library has performance issues in certain functions

Off the top of your head, which functions do you think have much potential for optimization? Is `isValid` among them?

Context: In https://github.com/commercialhaskell/path/issues/69 we're considering basically copying `isValid` into the `path` source in order to make our semantics independent from the installed `filepath` version.

If `isValid` can be optimized I'd prefer optimizing it first and copying it later…

**Comment by ndmitchell** [comment]
Basically most functions could be optimised, if they were every bottlenecks. But I'm not sure they ever have been - if you have a large number of filepaths you probably did some IO to get them, and that probably dominates. I have no plans for performance work in the near future.

**Comment by sjakobi** [comment]
`stack` had some performance issues with parsing `Path`s and we want to look into that [here](https://github.com/commercialhaskell/path/issues/63). My current assumption is that `isValid` is the most expensive part of parsing a `Path`.

**Comment by ndmitchell** [comment]
Entirely possible - I imagine you could write a fold over the list as a state machine that would be way more efficient. Personally I'd probably QuickCheck it against filepath but reimplement from scratch.

**Comment by ndmitchell** [comment]
Closing this ticket - if people can supply `.prof`'s pointing at specific functions, or patches to improve performance, we can take it from there.
