### ISSUE TITLE
Allow QuickCheck 2.10

### ISSUE THREAD

**Issue by ndmitchell** [haskell/filepath#59]
QuickCheck 2.10 is out. The upper bound in the test needs weakening. I'm guessing removing the upper bound is considered heresy for boot libraries? After I remove the upper bound, should I release a new version to Hackage, or will that screw up something? Should I only release with GHC releases?

CC @hvr

**Comment by erikd** [comment]
> Should I only release with GHC releases?

I'm pretty sure the answer to this is "as long as you follow the PVP, you can release whenever you like". At least that should be the answer.

**Comment by hvr** [comment]
@ndmitchell Well, yes; GHC boot libraries are expected to set a good example re versioning policy and upper bounds. You can release new versions to Hackage outside of GHC releases (there's no hard reason not to), but doing so merely for relaxing version constraints of a testsuite is frowned upon (even more so for benchmark suites), as this has no benefit and only results in index-meta-data, given the testsuite is an optional component which is irrelevant for install-plans. So the Hackage Trustee position re meta-data maintenance (see also the [cookbook here](https://github.com/haskell-infra/hackage-trustees/blob/master/cookbook.md) for more about meta-data maintenance near the end), is to avoid uploading releases or performing meta-data revisions if the sole purpose is to relax constraints in testsuites/benchmarks.

**Comment by ndmitchell** [comment]
OK, I've relaxed the bound in the repo and will leave it at that. I note my opinions on these things are quite different (no upper bounds, always release so the test suite can be built) - but happy to follow the official positions for a boot library.
