### ISSUE TITLE
Fix the Appveyor build

### ISSUE THREAD

**Issue by ndmitchell** [haskell/filepath#72]
https://ci.appveyor.com/project/ndmitchell/filepath is failing. The problem is that it doesn't find `time` on the plan. Trying the same project but renaming `filepath` to anything else fixes the issue, so it seems to be that by putting `filepath` in the plan it invalidates `time` somehow. A Stack bug, but I'm not convinced one they'll necessarily want to fix, as overwriting `filepath` is an odd thing to do.

**Comment by ndmitchell** [comment]
No progress on this from the Stack side, and it's a bit of an odd case, so I remove the Appveyor script in 2b7adb0b9c709dc5f354bff5cc4f72a9c860a35b.

**Comment by Rufflewind** [comment]
FWIW, `directory` was able to migrate from AppVeyor + Travis CI to a hand-crafted GitHub Actions config: https://github.com/haskell/directory/blob/master/.github/workflows/build.yml

The initial setup took some time to figure out -- the lack of standardization didn't help -- but past the learning curve it's actually pretty convenient and low-maintenance. Not having to deal with *two* CI services (AppVeyor + Travis CI) was a nice perk.

**Comment by Rufflewind** [comment]
Sorry, I meant to say `QuickCheck >= 2.7 && < 2.14`, which prevents filepath tests from building on GHC 9.0.

**Comment by ndmitchell** [comment]
I've moved all my other projects to GitHub actions and agree it's clearly the best way to go. However, I'm in the process of transferring maintainership, so think the new maintainer should have choice of which CI to use, and how to configure it etc: https://github.com/haskell/filepath/issues/79

**Comment by hasufell** [comment]
https://github.com/haskell/filepath/pull/89
