### ISSUE TITLE
Find an alternative maintainer

### ISSUE THREAD

**Issue by ndmitchell** [haskell/filepath#79]
My interest in maintaining this library is waning. There are a bunch of minor but interesting discussions to be had (e.g. #73) and maintenance work to change or not-change CI (e.g. #77). I don't typically follow the approach or tooling of the other libraries maintained by the CLC, and have little interest in starting. All these factors combined make me think that finding a new maintainer is not a bad idea.

CC @haskell/core-libraries-committee

**Comment by chessai** [comment]
Ah, was meaning to talk to you about this after reading your comments on
GitHub.

I think this is a good idea.

Thank you for the time and work you've put in thus far. I will begin
looking for a new maintainer. Anyone on the CLC can step in if they want,
at least hopefully as an interim? I have no interest in maintaining
filepath long-term (or even short term) myself. I am not super worried
since filepath is pretty stable.

Looping in phadej and bgamari since they may have good ideas for
maintainers.

**Comment by chessai** [comment]
- I'd ask `directory` maintainers. These two libraries are closely related.
- I'd avoid people with opinionated ideas on how path library should
look like (e.g. authors of `path`, `hpath`, `paths`, ...), except if CLC
wants filepaths in base to move into some of the packages' direction
- Windows experience is a plus (4 of 13 of open issues is about that)

- Oleg

**Comment by chessai** [comment]
Thanks Oleg,

Those are great guidelines.

**Comment by ndmitchell** [comment]
Any progress on finding an alternative maintainer? I note the CI system is currently under my personal Travis, and it should probably be moved to a central one, or personal one of the new maintainer, at the same time as considering #77 from @phadej.

**Comment by fendor** [comment]
Any updates on this?

**Comment by chessai** [comment]
> Any updates on this?

I've reached out to a potential maintainer just a few moments ago. Waiting to hear back.

**Comment by Bodigrim** [comment]
Dear CLC members, as we [discussed internally](https://groups.google.com/g/haskell-core-libraries/c/Z93zUA_QVw0), `filepath` still needs a maintainer. @hasufell has kindly signalled that he could be interested to take on the burden. I suggest we approve him as a new maintainer of `filepath`, please vote below.
CC @chessai @cgibbard @emilypi @cigsender @gwils 

----

+1 from myself.

**Comment by cigsender** [comment]
+1 from me!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by chessai** [comment]
+1

**Comment by emilypi** [comment]
+1 here

**Comment by gwils** [comment]
+1

**Comment by Bodigrim** [comment]
Thanks, seems we have a majority in favor.

@chessai @emilypi could you please give @hasufell access rights to GitHub repo?
@gbaz could you please grant https://hackage.haskell.org/user/maerwald maintainership of [`filepath`](https://hackage.haskell.org/package/filepath)?

**Comment by chessai** [comment]
> Thanks, seems we have a majority in favor.
> 
> @chessai @emilypi could you please give @hasufell access rights to GitHub repo? @gbaz could you please grant https://hackage.haskell.org/user/maerwald maintainership of [`filepath`](https://hackage.haskell.org/package/filepath)?

@hasufell you should now have admin rights on this repo. Or at least an invitation to gain them (GitHub didn't make it clear which was the case).

**Comment by hesselink** [comment]
I've added maerwald as a maintainer on hackage.
