### ISSUE TITLE
Haddock "#Source" links are uninformative

### ISSUE THREAD

**Issue by andreasabel** [haskell/filepath#81]
For any function on https://hackage.haskell.org/package/filepath-1.4.2.1/docs/System-FilePath-Posix.html, if I click on `# Source`, I just see this:
```haskell
{-# LANGUAGE CPP #-}
#define MODULE_NAME     Posix
#define IS_WINDOWS      False
#include "Internal.hs"
```
This does not allow me to navigate to the point of interest in the source code.

**Comment by hasufell** [comment]
@Kleidukos is there a known fix for this problem?

**Comment by Kleidukos** [comment]
Not that I know of, and worse, might even be related to how GHC gives us the info about the source code. :/

**Comment by hasufell** [comment]
This is released: https://hackage.haskell.org/package/filepath-1.4.2.2
