### ISSUE TITLE
Document relation between `joinPath` and `</>`

### ISSUE THREAD

**Issue by andreasabel** [haskell/filepath#82]
I would expect that `joinPath[a,b]` behaves exactly like `a </> b` (aka `combine a b`).  Unfortunately, the documentation does not enlighten me on the relationship between `joinPath` and `combine`.  Is `joinPath` just a fold using the monoid `mempty = ""; mappend = combine`?

I would have consulted the source code to clarify my question, but see #81.

Please document the relationship between `joinPath` and `combine`.

**Comment by andreasabel** [comment]
Cloning and grepping the git repo, I find `joinPath = foldr combine ""`.  This should be in the docs.

**Comment by ndmitchell** [comment]
Perfectly reasonable, and also your remark about sources in #81. Note the library is transitioning ownership through #79, so I will wait for the next maintainer to respond properly.
