### ISSUE TITLE
normalise doesn't remove '..'

### ISSUE THREAD

**Issue by yaitskov** [haskell/filepath#86]
Hi,

I would expect from `normalise` to remove '..' from path:

```
normalise "/a/b/../c" == "/a/c"
normalise "/.." == "/"
```

**Comment by ndmitchell** [comment]
Yeah, I expected that when I first started working on filepath. It's not correct though, because of symlinks, as per https://github.com/haskell/filepath/issues/87#issuecomment-955276974
