### ISSUE TITLE
equalFilePath returns False for "/a/.." and "/"

### ISSUE THREAD

**Issue by yaitskov** [haskell/filepath#87]
Hi,

equalFilePath doesn't take into account ".."

should be true:

```
equalFilePath "/" "/.."
equalFilePath "/a/../c" "/c"
```

**Comment by ndmitchell** [comment]
That's not right, because of symlinks. Imagine that `a` is a symlink to `foo/bar`, then `realpath /a/../c` would be `/foo/c` which isn't equal to `/c`.

**Comment by hasufell** [comment]
Maybe we should document that/why we're not doing this.
