### ISSUE TITLE
IsRelative is broken or perhaps depends on compilation target

### ISSUE THREAD

**Issue by TomMD** [haskell/filepath#88]
I'm trying to handle windows file paths in Linux and the isRelative function is behaving in a manner contrary to the documentation:

```
% ghci-9.2.1
GHCi, version 9.2.1: https://www.haskell.org/ghc/  :? for help
Loaded GHCi configuration from /Users/tommd/.ghci
ghci> import System.FilePath
ghci> isRelative "C:/foo"
True
ghci> isRelative "C:\\foo"
True
ghci> isRelative "c:\\foo"
True
ghci> isRelative "c:\\test"
True
```

N.B. the haddocs say:

```
Windows: isRelative "c:\\test" == False
```

**Comment by TomMD** [comment]
I now [see](https://github.com/haskell/filepath/blob/master/System/FilePath/Internal.hs#L419) this is a compilation dependent function and am sad.  We should fix the documentation, just saying "windows" and "posix" before an example doesn't clearly translate to "this is how it will behave when compiled on/for windows but it will behave differently otherwise".

**Comment by hasufell** [comment]
I believe the documentation is clear enough:

https://github.com/haskell/filepath/blob/738317a0074e0d68a5e67610d3f43cee23301105/System/FilePath.hs#L14-L19
